"""clean schema with named constraints

Revision ID: 553dffc935ae
Revises: 
Create Date: 2026-01-27 21:46:36.497202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553dffc935ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_plants_name')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name='fk_readings_plant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin', name='uq_sensors_pin'),
    sa.UniqueConstraint('plant_id', name='uq_sensors_plant_id')
    )
    op.create_table('humidity_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name='fk_readings_sensor_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('humidity_readings')
    op.drop_table('sensors')
    op.drop_table('plants')
    # ### end Alembic commands ###
