"""add unique constraint to plant name

Revision ID: 6c0883479c1c
Revises: a869652157f0
Create Date: 2026-01-25 22:29:44.004185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0883479c1c'
down_revision = 'a869652157f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_plants_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plants_name', type_='unique')

    # ### end Alembic commands ###
