"""add unique constraint on name in Plants model

Revision ID: 736e7c9df86f
Revises: a869652157f0
Create Date: 2026-01-25 14:50:27.605705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736e7c9df86f'
down_revision = 'a869652157f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
